Repository 12products/warroom-frontend, pull requests merged in 2022-03, with the labels that each got.

#35 fix: Form input fixes
  src/components/forms/CreateActionItemForm.tsx
  src/components/forms/CreateEventForm.tsx
  src/components/forms/CreateIncidentForm.tsx
  src/components/forms/CreateStatusMessageForm.tsx
Labels: bug

#39 feat: add settings page
  src/components/AuthForm.tsx
  src/components/DropdownOption.tsx
  src/components/UserMenu.tsx
  src/components/forms/OnboardForm.tsx
  src/components/forms/SignInForm.tsx
  src/components/forms/SignUpForm.tsx
  src/components/forms/UpdateUserForm.tsx
  src/components/layouts/AppNav.tsx
  src/pages/onboard.tsx
  src/pages/settings.tsx
  src/routes.ts
Labels: enhancement

#40 feat: add event type
  src/components/FormToggle.tsx
  src/components/IncidentSummary.tsx
  src/components/forms/CreateEventForm.tsx
  src/components/forms/UpdateServiceForm.tsx
  src/pages/incidents/[id]/index.tsx
  src/types/Incident.ts
  src/types/event.ts
Labels: enhancement

#44 chore: fix up issues with statuses
  src/components/CurrentStatus.tsx
  src/components/forms/OnboardForm.tsx
  src/components/forms/UpdateUserForm.tsx
  src/components/layouts/AppNav.tsx
  src/pages/status.tsx
Labels: bug, enhancement

#43 feat: make War Room global across the app
  src/App.tsx
  src/components/IncidentWarRoom.tsx
  src/components/layouts/AppNav.tsx
  src/components/modals/WarRoomModal.tsx
  src/context/AuthProvider.tsx
  src/context/WarRoomProvider.tsx
Labels: enhancement

#45 chore: clean up lots of stuff
  src/components/CurrentStatus.tsx
  src/components/IncidentRow.tsx
  src/components/IncidentsByDate.tsx
  src/pages/incidents/assigned.tsx
  src/pages/incidents/index.tsx
  src/pages/incidents/open.tsx
  src/pages/incidents/service.tsx
  src/pages/status.tsx
Labels: bug, enhancement

#46 feat: Add date to event and update queries on create
  src/components/CurrentStatus.tsx
  src/components/Dropdown.tsx
  src/components/DropdownOption.tsx
  src/components/FormDropdown.tsx
  src/components/FormToggle.tsx
  src/components/IncidentActionItem.tsx
  src/components/IncidentActionItems.tsx
  src/components/IncidentDetails.tsx
  src/components/IncidentEvent.tsx
  src/components/IncidentEvents.tsx
  src/components/IncidentProperties.tsx
  src/components/IncidentProperty.tsx
  src/components/IncidentStatuses.tsx
  src/components/IncidentsSidebar.tsx
  src/components/forms/CreateEventForm.tsx
  src/components/forms/CreateIncidentForm.tsx
  src/components/forms/CreateStatusMessageForm.tsx
  src/components/modals/CreateEvent.tsx
  src/components/modals/CreateEventButton.tsx
  src/components/modals/CreateIncidentButton.tsx
  src/components/modals/CreateStatusMessage.tsx
  src/components/modals/StatusMessageButton.tsx
  src/pages/incidents/[id]/index.tsx
  src/pages/incidents/assigned.tsx
  src/pages/incidents/index.tsx
  src/types/Incident.ts
  src/types/index.ts
  src/types/ui.ts
Labels: enhancement

#47 feat: allow users to be invited
  src/components/AuthForm.tsx
  src/components/CurrentStatus.tsx
  src/components/IncidentProperty.tsx
  src/components/IncidentsTable.tsx
  src/components/InviteRow.tsx
  src/components/InviteSection.tsx
  src/components/OrganizationMembers.tsx
  src/components/ServiceCard.tsx
  src/components/UserMenu.tsx
  src/components/forms/OnboardForm.tsx
  src/components/forms/OnboardFormWithOrg.tsx
  src/components/forms/OnboardFormWithoutOrg.tsx
  src/components/layouts/AppNav.tsx
  src/components/modals/CreateEventButton.tsx
  src/components/modals/CreateEventModal.tsx
  src/components/modals/InviteModal.tsx
  src/pages/onboard.tsx
  src/pages/settings.tsx
  src/types/invite.ts
Labels: enhancement
